export type { ICustomersRepository } from './customers-repository'
export type { IPetsRepository } from './pets-repository'
export type { IProductsRepository } from './products-repository'
export type { IServicesRepository } from './services-repository'
export type { IOrdersRepository } from './orders-repository'
