export { CustomersFaker } from './customers-faker'
export { PetsFaker } from './pets-faker'
export { PhonesFaker } from './phones-faker'
export { ProductsFaker } from './products-faker'
export { ServicesFaker } from './services-faker'
